"""add last_updated_at to user quest progress

Revision ID: 355bcdb58274
Revises: 6a3091b27976
Create Date: 2026-05-12 17:26:16.138260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355bcdb58274'
down_revision: Union[str, Sequence[str], None] = '6a3091b27976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_quest_progress', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_quest_progress', 'last_updated_at')
    # ### end Alembic commands ###
