"""Add reward_type to Quest

Revision ID: 97c9c185cb9f
Revises: de90d4c4b690
Create Date: 2026-05-12 16:31:16.461890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c9c185cb9f'
down_revision: Union[str, Sequence[str], None] = 'de90d4c4b690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('reward_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'reward_type')
    # ### end Alembic commands ###
