"""Add vector embedding column

Revision ID: b000c8613de0
Revises: a35185d6997e
Create Date: 2026-05-10 14:54:59.717569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'b000c8613de0'
down_revision: Union[str, Sequence[str], None] = 'a35185d6997e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'embedding')
    # ### end Alembic commands ###
