"""add spins_left

Revision ID: cddcb1e8e078
Revises: 0077423b7c31
Create Date: 2026-05-10 16:49:33.434568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cddcb1e8e078'
down_revision: Union[str, Sequence[str], None] = '0077423b7c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spins_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spins_left')
    # ### end Alembic commands ###
