"""Add order management and logistics tables

Revision ID: d117696debf6
Revises: 5993b2945ced
Create Date: 2026-05-10 19:34:36.880833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd117696debf6'
down_revision: Union[str, Sequence[str], None] = '5993b2945ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually handle enum updates
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PACKED'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'PAYMENT_FAILED'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'RETURN_REQUESTED'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'RETURNED'")
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'CLOSED'")

    # Create new enum
    order_actor = postgresql.ENUM('SYSTEM', 'USER', 'SELLER', 'ADMIN', name='orderactor')
    order_actor.create(op.get_bind())

    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', postgresql.ENUM(name='orderstatus', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM(name='orderstatus', create_type=False), nullable=False),
    sa.Column('actor', postgresql.ENUM(name='orderactor', create_type=False), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=False),
    sa.Column('tracking_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('estimated_delivery', sa.DateTime(), nullable=True),
    sa.Column('last_location', sa.String(), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order_items', sa.Column('product_title', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('product_image', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('billing_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'billing_address')
    op.drop_column('order_items', 'product_image')
    op.drop_column('order_items', 'product_title')
    op.drop_table('return_items')
    op.drop_table('shipments')
    op.drop_table('returns')
    op.drop_table('order_events')
    op.drop_table('outbox')
    
    # Drop enum
    sa.Enum(name='orderactor').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
