"""Add target_user_role and is_active to Quest

Revision ID: de90d4c4b690
Revises: 3fdbbaea88e1
Create Date: 2026-05-12 16:17:28.860598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de90d4c4b690'
down_revision: Union[str, Sequence[str], None] = '3fdbbaea88e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('target_user_role', sa.String(), nullable=True))
    op.add_column('quests', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'is_active')
    op.drop_column('quests', 'target_user_role')
    # ### end Alembic commands ###
